update version 1.1.8, add fixes to lets encrypt example

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -1,33 +1,37 @@
 FROM php:%%PHP_VERSION%%-%%VARIANT%%
 
 RUN apt-get update && apt-get install -y cron git-core jq unzip vim zip \
-  libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
-  rm -rf /var/lib/apt/lists/* && \
-  %%PHP_ZIP_CONFIG%% && \
-  %%PHP_GD_CONFIG%% && \
-  docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
+	libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
+	rm -rf /var/lib/apt/lists/* && \
+	%%PHP_ZIP_CONFIG%% && \
+	%%PHP_GD_CONFIG%% && \
+	docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
+
+# Use the default production configuration
+RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
 
 # Recommended opcache settings - https://secure.php.net/manual/en/opcache.installation.php
 RUN { \
-    echo 'opcache.memory_consumption=128'; \
-    echo 'opcache.interned_strings_buffer=8'; \
-    echo 'opcache.max_accelerated_files=4000'; \
-    echo 'opcache.revalidate_freq=2'; \
-    echo 'opcache.fast_shutdown=1'; \
-    echo 'opcache.enable_cli=1'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
+	echo 'opcache.memory_consumption=128'; \
+	echo 'opcache.interned_strings_buffer=8'; \
+	echo 'opcache.max_accelerated_files=4000'; \
+	echo 'opcache.revalidate_freq=2'; \
+	echo 'opcache.fast_shutdown=1'; \
+	echo 'opcache.enable_cli=1'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
 
 RUN { \
-    echo 'log_errors=on'; \
-    echo 'display_errors=off'; \
-    echo 'upload_max_filesize=32M'; \
-    echo 'post_max_size=32M'; \
-    echo 'memory_limit=128M'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-php.ini
+	echo 'log_errors=on'; \
+	echo 'display_errors=off'; \
+	echo 'upload_max_filesize=32M'; \
+	echo 'post_max_size=32M'; \
+	echo 'memory_limit=128M'; \
+	echo 'expose_php=off'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-php.ini
 
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
-RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer 
+RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer
 
 %%VARIANT_EXTRAS%%
 
@@ -40,29 +44,29 @@ ENV WINTERCMS_CORE_BUILD %%WINTERCMS_CORE_BUILD%%
 
 # Consolidated Winter CMS setup
 RUN git clone https://github.com/wintercms/winter.git -b $WINTERCMS_TAG --depth 1 . && \
-  # match build dependencies
-  echo "Update composer.json: Set explicit build references for winter module dependencies" && \
-  sed -i.orig "s/\(\"winter\/\([storm|system|backend|cms]*\)\": \"\(~1.0\)\"\)/\"winter\/\2\": \"<=${WINTERCMS_TAG#v}\"/g" composer.json && \
-  egrep -o "['\"]winter\/[storm|system|backend|cms]*['\"]\s*:\s*['\"](.+?)['\"]" composer.json && \
-  # download dependencies
-  composer install --no-interaction --prefer-dist --no-scripts && \
-  composer clearcache && \
-  # ensure modules are in sync with the repo after composer install
-  git status && git checkout modules/. && \
-  # remove git repo
-  rm -rf .git && \
-  # setup docker env
-  echo 'APP_ENV=docker' > .env && \
-  mv /usr/src/wintercms-config-docker config/docker && \
-  # setup database
-  touch storage/database.sqlite && \
-  chmod 666 storage/database.sqlite && \
-  php artisan winter:up && \
-  # add Winter Drivers
-  # php artisan plugin:install winter.drivers && \
-  # permissions
-  chown -R www-data:www-data /var/www/html && \
-  find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
+	# match build dependencies
+	echo "Update composer.json: Set explicit build references for winter module dependencies" && \
+	sed -i.orig "s/\(\"winter\/\([storm|system|backend|cms]*\)\": \"\(~1.0\)\"\)/\"winter\/\2\": \"<=${WINTERCMS_TAG#v}\"/g" composer.json && \
+	egrep -o "['\"]winter\/[storm|system|backend|cms]*['\"]\s*:\s*['\"](.+?)['\"]" composer.json && \
+	# download dependencies
+	composer install --no-interaction --prefer-dist --no-scripts && \
+	composer clearcache && \
+	# ensure modules are in sync with the repo after composer install
+	git status && git checkout modules/. && \
+	# remove git repo
+	rm -rf .git && \
+	# setup docker env
+	echo 'APP_ENV=docker' > .env && \
+	mv /usr/src/wintercms-config-docker config/docker && \
+	# setup database
+	touch storage/database.sqlite && \
+	chmod 666 storage/database.sqlite && \
+	php artisan winter:up && \
+	# add Winter Drivers
+	# php artisan plugin:install winter.drivers && \
+	# permissions
+	chown -R www-data:www-data /var/www/html && \
+	find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
 
 # Set Winter build params
 # RUN php -r "use System\\Models\\Parameter; \
@@ -74,14 +78,14 @@ RUN git clone https://github.com/wintercms/winter.git -b $WINTERCMS_TAG --depth 
 
 # Initialize crontab for the Winter CMS scheduler
 RUN echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run > /proc/1/fd/1 2>/proc/1/fd/2" > /etc/cron.d/winter-cron && \
-  crontab /etc/cron.d/winter-cron
+	crontab /etc/cron.d/winter-cron
 
 # Add helpers
 RUN echo 'exec php artisan "$@"' > /usr/local/bin/artisan && \
-  echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
-  echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
-  sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
-  chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
+	echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
+	echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
+	sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
+	chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
 
 COPY docker-wn-entrypoint /usr/local/bin/
 
diff --git a/php7.2/fpm/Dockerfile.develop b/php7.2/fpm/Dockerfile.develop
--- a/php7.2/fpm/Dockerfile.develop
+++ b/php7.2/fpm/Dockerfile.develop
@@ -1,37 +1,37 @@
 FROM php:7.2-fpm
 
 RUN apt-get update && apt-get install -y cron git-core jq unzip vim zip \
-  libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
-  rm -rf /var/lib/apt/lists/* && \
-  docker-php-ext-configure zip --with-libzip && \
-  docker-php-ext-configure gd --with-png-dir --with-jpeg-dir --with-webp-dir && \
-  docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
+	libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
+	rm -rf /var/lib/apt/lists/* && \
+	docker-php-ext-configure zip --with-libzip && \
+	docker-php-ext-configure gd --with-png-dir --with-jpeg-dir --with-webp-dir && \
+	docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
 
 RUN { \
-    echo 'opcache.memory_consumption=128'; \
-    echo 'opcache.interned_strings_buffer=8'; \
-    echo 'opcache.max_accelerated_files=4000'; \
-    echo 'opcache.revalidate_freq=2'; \
-    echo 'opcache.fast_shutdown=1'; \
-    echo 'opcache.enable_cli=1'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
+	echo 'opcache.memory_consumption=128'; \
+	echo 'opcache.interned_strings_buffer=8'; \
+	echo 'opcache.max_accelerated_files=4000'; \
+	echo 'opcache.revalidate_freq=2'; \
+	echo 'opcache.fast_shutdown=1'; \
+	echo 'opcache.enable_cli=1'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
 
 RUN { \
-    echo 'log_errors=on'; \
-    echo 'display_errors=off'; \
-    echo 'upload_max_filesize=32M'; \
-    echo 'post_max_size=32M'; \
-    echo 'memory_limit=128M'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-php.ini
+	echo 'log_errors=on'; \
+	echo 'display_errors=off'; \
+	echo 'upload_max_filesize=32M'; \
+	echo 'post_max_size=32M'; \
+	echo 'memory_limit=128M'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-php.ini
 
 RUN pecl install xdebug
 
 RUN { \
-    echo "#zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" ; \
-    echo 'xdebug.remote_enable=on'; \
-    echo 'xdebug.remote_autostart=off'; \
-    echo 'xdebug.remote_host=host.docker.internal'; \
-  } > /usr/local/etc/php/conf.d/docker-xdebug-php.ini
+	echo "#zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" ; \
+	echo 'xdebug.remote_enable=on'; \
+	echo 'xdebug.remote_autostart=off'; \
+	echo 'xdebug.remote_host=host.docker.internal'; \
+	} > /usr/local/etc/php/conf.d/docker-xdebug-php.ini
 
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
@@ -42,30 +42,37 @@ RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/l
 COPY config/docker /usr/src/wintercms-config-docker
 
 ENV WINTERCMS_TAG develop
-ENV WINTERCMS_DEVELOP_CHECKSUM 3dd3689242c764602b908ccc317ab589a5cbe61e
-ENV WINTERCMS_DEVELOP_COMMIT 6bbfd0e885e8225bd06db91ae278cef64ef5a708
+ENV WINTERCMS_DEVELOP_CHECKSUM d9b17270d4f188ebbf3fe9d8dff97515fa1e72c5
+ENV WINTERCMS_DEVELOP_COMMIT f58633cd458937ac20d07d672a77ebc28264224a
 
 RUN git clone https://github.com/wintercms/winter.git -b $WINTERCMS_TAG . && \
-  composer install --no-interaction --prefer-dist --no-scripts && \
-  composer clearcache && \
-  git status && git checkout modules/. && \
-  echo 'APP_ENV=docker' > .env && \
-  mv /usr/src/wintercms-config-docker config/docker && \
-  echo 'config/docker' >> .git/info/exclude && \
-  touch storage/database.sqlite && \
-  chmod 666 storage/database.sqlite && \
-  php artisan winter:up && \
-  chown -R www-data:www-data /var/www/html && \
-  find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
+	# download dependencies
+	composer install --no-interaction --prefer-dist --no-scripts && \
+	composer clearcache && \
+	# ensure modules are in sync with the repo after composer install
+	git status && git checkout modules/. && \
+	# setup docker env
+	echo 'APP_ENV=docker' > .env && \
+	mv /usr/src/wintercms-config-docker config/docker && \
+	echo 'config/docker' >> .git/info/exclude && \
+	# setup database
+	touch storage/database.sqlite && \
+	chmod 666 storage/database.sqlite && \
+	php artisan winter:up && \
+	# add Winter Drivers
+	# php artisan plugin:install winter.drivers && \
+	# permissions
+	chown -R www-data:www-data /var/www/html && \
+	find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
 
 RUN echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run > /proc/1/fd/1 2>/proc/1/fd/2" > /etc/cron.d/winter-cron && \
-  crontab /etc/cron.d/winter-cron
+	crontab /etc/cron.d/winter-cron
 
 RUN echo 'exec php artisan "$@"' > /usr/local/bin/artisan && \
-  echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
-  echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
-  sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
-  chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
+	echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
+	echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
+	sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
+	chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
 
 COPY docker-wn-entrypoint /usr/local/bin/
 
diff --git a/php7.4/apache/Dockerfile b/php7.4/apache/Dockerfile
--- a/php7.4/apache/Dockerfile
+++ b/php7.4/apache/Dockerfile
@@ -1,66 +1,78 @@
 FROM php:7.4-apache
 
 RUN apt-get update && apt-get install -y cron git-core jq unzip vim zip \
-  libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
-  rm -rf /var/lib/apt/lists/* && \
-  docker-php-ext-configure zip --with-zip && \
-  docker-php-ext-configure gd --with-jpeg --with-webp && \
-  docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
+	libjpeg-dev libpng-dev libpq-dev libsqlite3-dev libwebp-dev libzip-dev && \
+	rm -rf /var/lib/apt/lists/* && \
+	docker-php-ext-configure zip --with-zip && \
+	docker-php-ext-configure gd --with-jpeg --with-webp && \
+	docker-php-ext-install exif gd mysqli opcache pdo_pgsql pdo_mysql zip
+
+RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
 
 RUN { \
-    echo 'opcache.memory_consumption=128'; \
-    echo 'opcache.interned_strings_buffer=8'; \
-    echo 'opcache.max_accelerated_files=4000'; \
-    echo 'opcache.revalidate_freq=2'; \
-    echo 'opcache.fast_shutdown=1'; \
-    echo 'opcache.enable_cli=1'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
+	echo 'opcache.memory_consumption=128'; \
+	echo 'opcache.interned_strings_buffer=8'; \
+	echo 'opcache.max_accelerated_files=4000'; \
+	echo 'opcache.revalidate_freq=2'; \
+	echo 'opcache.fast_shutdown=1'; \
+	echo 'opcache.enable_cli=1'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-opcache.ini
 
 RUN { \
-    echo 'log_errors=on'; \
-    echo 'display_errors=off'; \
-    echo 'upload_max_filesize=32M'; \
-    echo 'post_max_size=32M'; \
-    echo 'memory_limit=128M'; \
-  } > /usr/local/etc/php/conf.d/docker-wn-php.ini
+	echo 'log_errors=on'; \
+	echo 'display_errors=off'; \
+	echo 'upload_max_filesize=32M'; \
+	echo 'post_max_size=32M'; \
+	echo 'memory_limit=128M'; \
+	echo 'expose_php=off'; \
+	} > /usr/local/etc/php/conf.d/docker-wn-php.ini
 
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
-RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer 
+RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer
 
 RUN a2enmod rewrite
 
 COPY config/docker /usr/src/wintercms-config-docker
 
-ENV WINTERCMS_TAG v1.1.7
-ENV WINTERCMS_CHECKSUM 84213f77b2d9e3cd778fdc9d1ba0ff217bd714a9
-ENV WINTERCMS_CORE_BUILD v1.1.7
+ENV WINTERCMS_TAG v1.1.8
+ENV WINTERCMS_CHECKSUM 45bc2f105dcd004ddd37e7d0389c997daaf66cdc
+ENV WINTERCMS_CORE_BUILD v1.1.8
 
 RUN git clone https://github.com/wintercms/winter.git -b $WINTERCMS_TAG --depth 1 . && \
-  echo "Update composer.json: Set explicit build references for winter module dependencies" && \
-  sed -i.orig "s/\(\"winter\/\([storm|system|backend|cms]*\)\": \"\(~1.0\)\"\)/\"winter\/\2\": \"<=${WINTERCMS_TAG#v}\"/g" composer.json && \
-  egrep -o "['\"]winter\/[storm|system|backend|cms]*['\"]\s*:\s*['\"](.+?)['\"]" composer.json && \
-  composer install --no-interaction --prefer-dist --no-scripts && \
-  composer clearcache && \
-  git status && git checkout modules/. && \
-  rm -rf .git && \
-  echo 'APP_ENV=docker' > .env && \
-  mv /usr/src/wintercms-config-docker config/docker && \
-  touch storage/database.sqlite && \
-  chmod 666 storage/database.sqlite && \
-  php artisan winter:up && \
-  chown -R www-data:www-data /var/www/html && \
-  find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
+	# match build dependencies
+	echo "Update composer.json: Set explicit build references for winter module dependencies" && \
+	sed -i.orig "s/\(\"winter\/\([storm|system|backend|cms]*\)\": \"\(~1.0\)\"\)/\"winter\/\2\": \"<=${WINTERCMS_TAG#v}\"/g" composer.json && \
+	egrep -o "['\"]winter\/[storm|system|backend|cms]*['\"]\s*:\s*['\"](.+?)['\"]" composer.json && \
+	# download dependencies
+	composer install --no-interaction --prefer-dist --no-scripts && \
+	composer clearcache && \
+	# ensure modules are in sync with the repo after composer install
+	git status && git checkout modules/. && \
+	# remove git repo
+	rm -rf .git && \
+	# setup docker env
+	echo 'APP_ENV=docker' > .env && \
+	mv /usr/src/wintercms-config-docker config/docker && \
+	# setup database
+	touch storage/database.sqlite && \
+	chmod 666 storage/database.sqlite && \
+	php artisan winter:up && \
+	# add Winter Drivers
+	# php artisan plugin:install winter.drivers && \
+	# permissions
+	chown -R www-data:www-data /var/www/html && \
+	find . -type d \( -path './plugins' -or  -path './storage' -or  -path './themes' -or  -path './plugins/*' -or  -path './storage/*' -or  -path './themes/*' \) -exec chmod g+ws {} \;
 
 
 RUN echo "* * * * * /usr/local/bin/php /var/www/html/artisan schedule:run > /proc/1/fd/1 2>/proc/1/fd/2" > /etc/cron.d/winter-cron && \
-  crontab /etc/cron.d/winter-cron
+	crontab /etc/cron.d/winter-cron
 
 RUN echo 'exec php artisan "$@"' > /usr/local/bin/artisan && \
-  echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
-  echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
-  sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
-  chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
+	echo 'exec php artisan tinker' > /usr/local/bin/tinker && \
+	echo '[ $# -eq 0 ] && exec php artisan winter || exec php artisan winter:"$@"' > /usr/local/bin/winter && \
+	sed -i '1s;^;#!/bin/bash\n[ "$PWD" != "/var/www/html" ] \&\& echo " - Helper must be run from /var/www/html" \&\& exit 1\n;' /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter && \
+	chmod +x /usr/local/bin/artisan /usr/local/bin/tinker /usr/local/bin/winter
 
 COPY docker-wn-entrypoint /usr/local/bin/
 
